/**
 * Streamable HTTP transport entry — MCP spec 2025-03-26.
 *
 * Adds the canonical Streamable HTTP transport alongside the existing
 * stdio entry. Stateful sessions (the spec's default) — session ID is
 * generated by the server and returned via the `Mcp-Session-Id` header
 * on the initialization response, then echoed by the client on every
 * subsequent request.
 *
 * Auth: bearer token in the `Authorization` header, validated against
 * `ATLASENT_MCP_HTTP_BEARER`. The bearer is the per-deployment shared
 * secret a host (Claude Desktop, Cursor, an internal gateway) uses to
 * authenticate to this MCP server instance. The upstream AtlaSent API
 * key (`ATLASENT_API_KEY`) is separate and unchanged — it authenticates
 * this MCP server to the AtlaSent backend, not the host to the MCP
 * server.
 *
 * If `ATLASENT_MCP_HTTP_BEARER` is unset, requests are accepted without
 * bearer validation (single-tenant / loopback deploys). A clear stderr
 * warning is logged at startup so this is not a silent fallback.
 *
 * Session storage is in-process (single-instance deploys). Multi-instance
 * deploys would need a shared store — documented as a future upgrade in
 * V2_ROLLOUT.md (open question 1).
 */

import { createServer as createHttpServer, type IncomingMessage, type Server } from "node:http";
import { randomUUID } from "node:crypto";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { createServer as createMcpServer } from "./server.js";

const DEFAULT_PORT = 3333;
const DEFAULT_PATH = "/mcp";

export interface StreamableHttpOptions {
  port?: number;
  host?: string;
  path?: string;
  /** Override McpServer factory (tests). */
  mcpServerFactory?: () => McpServer;
}

export interface StreamableHttpHandle {
  server: Server;
  port: number;
  close: () => Promise<void>;
}

interface Session {
  transport: StreamableHTTPServerTransport;
  mcp: McpServer;
}

function jsonRpcError(id: unknown, code: number, message: string): string {
  return JSON.stringify({
    jsonrpc: "2.0",
    id: id ?? null,
    error: { code, message },
  });
}

function writeJsonError(
  res: import("node:http").ServerResponse,
  status: number,
  body: string,
): void {
  res.writeHead(status, { "Content-Type": "application/json" });
  res.end(body);
}

function parseBearer(req: IncomingMessage): string | undefined {
  const h = req.headers["authorization"];
  if (typeof h !== "string") return undefined;
  const m = /^Bearer\s+(.+)$/i.exec(h.trim());
  return m ? m[1] : undefined;
}

function readBody(req: IncomingMessage, maxBytes: number): Promise<string> {
  return new Promise((resolve, reject) => {
    let len = 0;
    const chunks: Buffer[] = [];
    req.on("data", (chunk: Buffer) => {
      len += chunk.length;
      if (len > maxBytes) {
        reject(new Error(`request body exceeds ${maxBytes} bytes`));
        req.destroy();
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    req.on("error", reject);
  });
}

function logEvent(event: string, data: Record<string, unknown>): void {
  process.stderr.write(
    JSON.stringify({ ts: new Date().toISOString(), event, ...data }) + "\n",
  );
}

/**
 * Start the Streamable HTTP MCP server. Returns a handle for graceful
 * shutdown (tests use this).
 *
 * Wired in addition to — not in place of — the stdio entry. Hosts that
 * speak stdio continue to spawn the existing `atlasent-mcp` binary;
 * hosts that speak Streamable HTTP point at the URL exposed here.
 */
export async function startStreamableHttp(
  options: StreamableHttpOptions = {},
): Promise<StreamableHttpHandle> {
  const port = options.port ?? Number(process.env.ATLASENT_MCP_HTTP_PORT ?? DEFAULT_PORT);
  const host = options.host ?? process.env.ATLASENT_MCP_HTTP_HOST ?? "127.0.0.1";
  const path = options.path ?? process.env.ATLASENT_MCP_HTTP_PATH ?? DEFAULT_PATH;
  const expectedBearer = process.env.ATLASENT_MCP_HTTP_BEARER;
  const maxBodyBytes = Number(process.env.ATLASENT_MCP_HTTP_MAX_BODY ?? 1_048_576);
  const mcpFactory = options.mcpServerFactory ?? createMcpServer;

  if (!expectedBearer) {
    logEvent("streamable_http.no_bearer_warning", {
      message:
        "ATLASENT_MCP_HTTP_BEARER not set — accepting requests without bearer validation",
    });
  }

  const sessions = new Map<string, Session>();

  const httpServer = createHttpServer(async (req, res) => {
    // CORS / OPTIONS handling kept minimal — Streamable HTTP is server-to-
    // server in the deployments we care about (host process → MCP server).
    if (req.method === "OPTIONS") {
      res.writeHead(204, {
        "Access-Control-Allow-Methods": "GET, POST, DELETE, OPTIONS",
        "Access-Control-Allow-Headers":
          "Authorization, Content-Type, Mcp-Session-Id, Accept",
        "Access-Control-Allow-Origin": req.headers.origin ?? "*",
      });
      res.end();
      return;
    }

    if (!req.url || !req.url.startsWith(path)) {
      writeJsonError(res, 404, jsonRpcError(null, -32601, "Unknown path"));
      return;
    }

    // Bearer auth — only checked when the deploy configured one.
    if (expectedBearer) {
      const bearer = parseBearer(req);
      if (bearer !== expectedBearer) {
        writeJsonError(res, 401, jsonRpcError(null, -32001, "Unauthorized"));
        return;
      }
    }

    const sessionHeader = req.headers["mcp-session-id"];
    const sessionId = Array.isArray(sessionHeader) ? sessionHeader[0] : sessionHeader;

    let body: unknown = undefined;
    if (req.method === "POST") {
      try {
        const raw = await readBody(req, maxBodyBytes);
        body = raw.length > 0 ? JSON.parse(raw) : undefined;
      } catch (e) {
        writeJsonError(
          res,
          400,
          jsonRpcError(null, -32700, e instanceof Error ? e.message : String(e)),
        );
        return;
      }
    }

    // Route to an existing session, or initialize a new one. The SDK
    // transport handles the initialization handshake itself; we just
    // wire it to the McpServer instance and forward the request.
    let session: Session | undefined = sessionId ? sessions.get(sessionId) : undefined;

    if (!session) {
      // Bootstrap a new session-bound transport + server pair. The
      // sessionIdGenerator is invoked by the transport during the
      // initialize response.
      const transport = new StreamableHTTPServerTransport({
        sessionIdGenerator: () => randomUUID(),
        onsessioninitialized: (newId: string) => {
          sessions.set(newId, { transport, mcp });
          logEvent("streamable_http.session_initialized", { session_id: newId });
        },
      });
      transport.onclose = () => {
        const sid = transport.sessionId;
        if (sid) sessions.delete(sid);
        logEvent("streamable_http.session_closed", { session_id: sid ?? null });
      };
      const mcp = mcpFactory();
      await mcp.connect(transport);
      session = { transport, mcp };
    }

    try {
      await session.transport.handleRequest(req, res, body);
    } catch (e) {
      logEvent("streamable_http.request_error", {
        error: e instanceof Error ? e.message : String(e),
      });
      if (!res.headersSent) {
        writeJsonError(
          res,
          500,
          jsonRpcError(null, -32603, "Internal transport error"),
        );
      }
    }
  });

  await new Promise<void>((resolve, reject) => {
    httpServer.once("error", reject);
    httpServer.listen(port, host, () => {
      httpServer.removeListener("error", reject);
      resolve();
    });
  });

  const boundPort = (httpServer.address() as { port: number } | null)?.port ?? port;
  logEvent("streamable_http.listening", {
    host,
    port: boundPort,
    path,
    bearer_required: Boolean(expectedBearer),
  });

  return {
    server: httpServer,
    port: boundPort,
    close: () =>
      new Promise<void>((resolve) => {
        for (const s of sessions.values()) {
          try {
            void s.transport.close();
          } catch {
            /* ignore */
          }
        }
        sessions.clear();
        httpServer.close(() => resolve());
      }),
  };
}
